import { Job } from "../models/Job.js";
import { JobStore } from "../store/job.js";

export class JobService {
  constructor(private readonly jobStore: JobStore) {}

  /**
   * Lists all jobs for a user with optional filtering and sorting
   */
  async list(
    userId: string,
    filters?: {
      status?: string;
      searchTerm?: string;
      sortBy?: "date" | "company";
      sortOrder?: "asc" | "desc";
    }
  ): Promise<Job[]> {
    if (!userId) {
      throw new Error("User ID is required");
    }

    if (filters && (filters.status || filters.searchTerm)) {
      return this.jobStore.findByUserWithFilters(userId, filters);
    }

    return this.jobStore.findAllByUser(userId);
  }

  /**
   * Get a specific job by ID (verifying user owns it)
   */
  async getById(userId: string, id: string): Promise<Job | null> {
    if (!userId || !id) {
      throw new Error("User ID and Job ID are required");
    }

    const job = await this.jobStore.findById(id);

    // Verify the job belongs to the user
    if (job && job.userId !== userId) {
      throw new Error("Unauthorized: Job does not belong to this user");
    }

    return job;
  }

  /**
   * Create a new job application
   */
  async create(
    userId: string,
    data: Omit<Job, "id" | "userId" | "createdAt" | "updatedAt">
  ): Promise<Job> {
    if (!userId) {
      throw new Error("User ID is required");
    }

    if (!data.company || !data.title) {
      throw new Error("Company and title are required");
    }

    const job = new Job({
      id: "", // Will be generated by Prisma
      userId,
      company: data.company,
      title: data.title,
      type: data.type,
      status: data.status,
      location: data.location,
      url: data.url,
      description: data.description,
      notes: data.notes,
      appliedAt: data.appliedAt,
    });

    return this.jobStore.create(job);
  }

  /**
   * Update an existing job application
   */
  async update(
    userId: string,
    id: string,
    updates: Partial<Job>
  ): Promise<Job> {
    if (!userId || !id) {
      throw new Error("User ID and Job ID are required");
    }

    const existingJob = await this.jobStore.findById(id);
    if (!existingJob) {
      throw new Error("Job not found");
    }

    if (existingJob.userId !== userId) {
      throw new Error("Unauthorized: Job does not belong to this user");
    }

    // Merge existing job with updates
    const updatedJob = new Job({
      id: existingJob.id,
      userId: existingJob.userId,
      company: updates.company || existingJob.company,
      title: updates.title || existingJob.title,
      type: updates.type || existingJob.type,
      status: updates.status || existingJob.status,
      location: updates.location !== undefined ? updates.location : existingJob.location,
      url: updates.url !== undefined ? updates.url : existingJob.url,
      description: updates.description !== undefined ? updates.description : existingJob.description,
      notes: updates.notes !== undefined ? updates.notes : existingJob.notes,
      appliedAt: updates.appliedAt !== undefined ? updates.appliedAt : existingJob.appliedAt,
      createdAt: existingJob.createdAt,
      updatedAt: new Date(),
    });

    return this.jobStore.update(updatedJob);
  }

  /**
   * Delete a job application
   */
  async delete(userId: string, id: string): Promise<void> {
    if (!userId || !id) {
      throw new Error("User ID and Job ID are required");
    }

    const existingJob = await this.jobStore.findById(id);
    if (!existingJob) {
      throw new Error("Job not found");
    }

    if (existingJob.userId !== userId) {
      throw new Error("Unauthorized: Job does not belong to this user");
    }

    return this.jobStore.delete(id);
  }
}
